#!/usr/bin/env bash
set -e

# Create data directories
mkdir -p /var/lib/name-route/mailbox

if command -v systemctl &>/dev/null; then
    systemctl daemon-reload
    systemctl enable --now nameroute
fi
